In [6]:
#IMPORT LIBRARIES
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.datasets import load_iris
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
import os


In [7]:
#READING THE DATASET
veriler = pd.read_csv('iris.csv')

In [8]:
#X IS INPUT Y IS OUTPUT
x = veriler.iloc[:,1:5].values #bağımsız değişkenler
#y = veriler.iloc[:,5:].values #bağımlı değişken
Y= veriler.Species.values
print(x[:5])
print(Y[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [9]:

encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
print(encoded_Y)
# convert integers to dummy variables (i.e. one hot encoded)
y = np_utils.to_categorical(encoded_Y)
y

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [10]:
#verilerin egitim ve test icin bolunmesi
from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.33, random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)

In [12]:
from keras.models import Sequential
from keras.layers import Dense
classifier=Sequential([Dense(3,input_shape=(4,),activation='relu'),
                       Dense(3,activation='relu'),
                       Dense(3,activation='softmax')])
classifier.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3)                 15        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 12        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 12        
Total params: 39
Trainable params: 39
Non-trainable params: 0
_________________________________________________________________


In [13]:
classifier.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [14]:
classifier.fit(x_train,y_train,batch_size=10,epochs=400)

Epoch 1/400
100/100 [==============================] - 0s 5ms/step - loss: 1.0989 - accuracy: 0.3400
Epoch 2/400
100/100 [==============================] - 0s 110us/step - loss: 1.0985 - accuracy: 0.3400
Epoch 3/400
100/100 [==============================] - 0s 140us/step - loss: 1.0985 - accuracy: 0.3400
Epoch 4/400
100/100 [==============================] - 0s 130us/step - loss: 1.0984 - accuracy: 0.3400
Epoch 5/400
100/100 [==============================] - 0s 150us/step - loss: 1.0984 - accuracy: 0.3400
Epoch 6/400
100/100 [==============================] - 0s 150us/step - loss: 1.0984 - accuracy: 0.2900
Epoch 7/400
100/100 [==============================] - 0s 140us/step - loss: 1.0983 - accuracy: 0.2400
Epoch 8/400
100/100 [==============================] - 0s 140us/step - loss: 1.0983 - accuracy: 0.3500
Epoch 9/400
100/100 [==============================] - 0s 130us/step - loss: 1.0983 - accuracy: 0.3500
Epoch 10/400
100/100 [==============================] - 0s 130us/step - los

100/100 [==============================] - 0s 110us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 80/400
100/100 [==============================] - 0s 120us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 81/400
100/100 [==============================] - 0s 110us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 82/400
100/100 [==============================] - 0s 120us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 83/400
100/100 [==============================] - 0s 90us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 84/400
100/100 [==============================] - 0s 101us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 85/400
100/100 [==============================] - 0s 110us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 86/400
100/100 [==============================] - 0s 110us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 87/400
100/100 [==============================] - 0s 90us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 88/400
100/100 [==============================] - 0s 100us/step - loss: 1

100/100 [==============================] - 0s 100us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 158/400
100/100 [==============================] - 0s 100us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 159/400
100/100 [==============================] - 0s 115us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 160/400
100/100 [==============================] - 0s 130us/step - loss: 1.0973 - accuracy: 0.3500
Epoch 161/400
100/100 [==============================] - 0s 130us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 162/400
100/100 [==============================] - 0s 120us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 163/400
100/100 [==============================] - 0s 120us/step - loss: 1.0973 - accuracy: 0.3500
Epoch 164/400
100/100 [==============================] - 0s 100us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 165/400
100/100 [==============================] - 0s 110us/step - loss: 1.0973 - accuracy: 0.3500
Epoch 166/400
100/100 [==============================] - 0s 112us/ste

100/100 [==============================] - 0s 110us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 235/400
100/100 [==============================] - 0s 110us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 236/400
100/100 [==============================] - 0s 120us/step - loss: 1.0973 - accuracy: 0.3500
Epoch 237/400
100/100 [==============================] - 0s 90us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 238/400
100/100 [==============================] - 0s 110us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 239/400
100/100 [==============================] - 0s 129us/step - loss: 1.0973 - accuracy: 0.3500
Epoch 240/400
100/100 [==============================] - 0s 110us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 241/400
100/100 [==============================] - 0s 110us/step - loss: 1.0975 - accuracy: 0.3500
Epoch 242/400
100/100 [==============================] - 0s 100us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 243/400
100/100 [==============================] - 0s 110us/step

100/100 [==============================] - 0s 149us/step - loss: 1.0973 - accuracy: 0.3500
Epoch 312/400
100/100 [==============================] - 0s 130us/step - loss: 1.0973 - accuracy: 0.3500
Epoch 313/400
100/100 [==============================] - 0s 120us/step - loss: 1.0973 - accuracy: 0.3500
Epoch 314/400
100/100 [==============================] - 0s 120us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 315/400
100/100 [==============================] - 0s 120us/step - loss: 1.0973 - accuracy: 0.3500
Epoch 316/400
100/100 [==============================] - 0s 130us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 317/400
100/100 [==============================] - 0s 130us/step - loss: 1.0973 - accuracy: 0.3500
Epoch 318/400
100/100 [==============================] - 0s 120us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 319/400
100/100 [==============================] - 0s 120us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 320/400
100/100 [==============================] - 0s 120us/ste

100/100 [==============================] - 0s 110us/step - loss: 1.0973 - accuracy: 0.3500
Epoch 390/400
100/100 [==============================] - 0s 100us/step - loss: 1.0973 - accuracy: 0.3500
Epoch 391/400
100/100 [==============================] - 0s 110us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 392/400
100/100 [==============================] - 0s 100us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 393/400
100/100 [==============================] - 0s 120us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 394/400
100/100 [==============================] - 0s 120us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 395/400
100/100 [==============================] - 0s 100us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 396/400
100/100 [==============================] - 0s 110us/step - loss: 1.0974 - accuracy: 0.3500
Epoch 397/400
100/100 [==============================] - 0s 120us/step - loss: 1.0973 - accuracy: 0.3500
Epoch 398/400
100/100 [==============================] - 0s 110us/ste